# Generated by Django 4.2 on 2023-06-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='unspecified', max_length=100)),
                ('industry', models.CharField(default='unspecified', max_length=50)),
                ('department', models.CharField(default='unspecified', max_length=50)),
                ('job_type', models.CharField(default='unspecified', max_length=50)),
                ('study_level', models.CharField(default='unspecified', max_length=50)),
                ('career_level', models.CharField(default='unspecified', max_length=50)),
                ('phone_number', models.CharField(default='unspecified', max_length=20)),
                ('job_title', models.CharField(default='unspecified', max_length=100)),
                ('job_description', models.TextField(default='unspecified', max_length=2000)),
                ('job_location', models.CharField(default='unspecified', max_length=50)),
                ('salary', models.CharField(default='unspecified', max_length=10)),
                ('posted_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('company_name', models.CharField(default='unspecified', max_length=50)),
                ('industry', models.CharField(default='unspecified', max_length=50)),
                ('phone_number', models.CharField(default='unspecified', max_length=20)),
                ('description', models.TextField(default='unspecified', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('full_name', models.CharField(default='unspecified', max_length=50)),
                ('phone_number', models.CharField(default='unspecified', max_length=20)),
                ('education', models.TextField(default='unspecified', max_length=500)),
                ('experience', models.TextField(default='unspecified', max_length=500)),
                ('skills', models.TextField(default='unspecified', max_length=500)),
                ('hobbies', models.TextField(default='unspecified', max_length=500)),
                ('foreign_languages', models.TextField(default='unspecified', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(blank=True, default='unspecified', on_delete=django.db.models.deletion.CASCADE, to='jobsite.ad')),
                ('user', models.ForeignKey(blank=True, default='unspecified', on_delete=django.db.models.deletion.CASCADE, to='jobsite.user')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='company',
            field=models.ForeignKey(blank=True, default='unspecified', on_delete=django.db.models.deletion.CASCADE, to='jobsite.company'),
        ),
    ]
